export enum ComplianceActionTypes {
  SET_COVENANT_COMPLIANCE_ACTIVE_KEY = "SET_COVENANT_COMPLIANCE_ACTIVE_KEY",
  GET_COVENANT_COMPLIANCE_LIST = "GET_COVENANT_COMPLIANCE_LIST",
  GET_COVENANT_COMPLIANCE_LIST_SUCCESS = "GET_COVENANT_COMPLIANCE_LIST_SUCCESS",
  GET_COVENANT_COMPLIANCE_LIST_FAILED = "GET_COVENANT_COMPLIANCE_LIST_FAILED",

  GET_COMPLIANCE_DETAILS = "GET_COMPLIANCE_DETAILS",
  GET_COMPLIANCE_DETAILS_SUCCESS = "GET_COMPLIANCE_DETAILS_SUCCESS",
  GET_COMPLIANCE_DETAILS_FAILED = "GET_COMPLIANCE_DETAILS_FAILED",
};