enum SOPActionTypes {
  'GET_SOP_APPLICANTS' = 'GET_SOP_APPLICANTS',
  'GET_SOP_APPLICANTS_SUCCESS' = 'GET_SOP_APPLICANTS_SUCCESS',
  'GET_SOP_APPLICANTS_FAIL' = 'GET_SOP_APPLICANTS_FAIL',
  
  'GET_SOP_PERIODS' = 'GET_SOP_PERIODS',
  'GET_SOP_PERIODS_SUCCESS' = 'GET_SOP_PERIODS_SUCCESS',
  'GET_SOP_PERIODS_FAIL' = 'GET_SOP_PERIODS_FAIL',
  
  'GET_SOP_SECTIONS' = 'GET_SOP_ASSETS',
  'GET_SOP_SECTIONS_SUCCESS' = 'GET_SOP_SECTIONS_SUCCESS',
  'GET_SOP_SECTIONS_FAIL' = 'GET_SOP_SECTIONS_FAIL',
  'ADD_SOP_SECTION' = 'ADD_SOP_SECTION',
  
  'SET_SOP_SUB_CURRENT_SUB_TAB_ID' = 'SET_SOP_SUB_CURRENT_SUB_TAB_ID',
  'SET_SOP_SUB_CURRENT_SUB_TAB_ID_SUCCESS' = 'SET_SOP_SUB_CURRENT_SUB_TAB_ID_SUCCESS',

  'SET_SOP_CURRENT_PERIOD' = 'SET_SOP_CURRENT_PERIOD',

  'GET_SOP_CATEGORYLIST' = 'GET_SOP_CATEGORYLIST',
  'GET_SOP_CATEGORYLIST_SUCCESS' = 'GET_SOP_CATEGORYLIST_SUCCESS',
  'GET_SOP_CATEGORYLIST_FAIL' = 'GET_SOP_CATEGORYLIST_FAIL',

  'SET_SOP_DETAIL_LOADING' = 'SET_SOP_DETAIL_LOADING',

  'SET_SOP_CURRENT_APPLICANT' = 'SET_SOP_CURRENT_APPLICANT',
}

export default SOPActionTypes;