enum DashboardActionTypes {
  'GET_DASHBOARD_COVENENT_SUMMARY' = 'GET_DASHBOARD_COVENENT_SUMMARY',
  'GET_DASHBOARD_COVENENT_SUMMARY_SUCCESS' = 'GET_DASHBOARD_COVENENT_SUMMARY_SUCCESS',

  'GET_DASHBOARD_SOP_SUMMARY' = 'GET_DASHBOARD_SOP_SUMMARY',
  'GET_DASHBOARD_SOP_SUMMARY_SUCCESS' = 'GET_DASHBOARD_SOP_SUMMARY_SUCCESS',

  'GET_DASHBOARD_DOCUMENT_SUMMARY' = 'GET_DASHBOARD_DOCUMENT_SUMMARY',
  'GET_DASHBOARD_DOCUMENT_SUMMARY_SUCCESS' = 'GET_DASHBOARD_DOCUMENT_SUMMARY_SUCCESS',
}

export default DashboardActionTypes;