export enum CovenantActionTypes {
  GET_COVENANT_LIST = "GET_COVENANT_LIST",
    GET_COVENANT_LIST_SUCCESS = "GET_COVENANT_LIST_SUCCESS",
    GET_COVENANT_LIST_FAILED = "GET_COVENANT_LIST_FAILED",

    GET_COVENANT_DETAILS = "GET_COVENANT_DETAILS",
    GET_COVENANT_DETAILS_SUCCESS = "GET_COVENANT_DETAILS_SUCCESS",
    GET_COVENANT_DETAILS_FAILED = "GET_COVENANT_DETAILS_FAILED",

    SET_COVENANT_ACTIVE_KEY = "SET_COVENANT_ACTIVE_KEY",
};